[ids]
*

[main]
leftcontrol = layer(ctrlq)
rightcontrol = layer(ctrlq)

# AltGr queda libre para símbolos del layout.
leftalt = layer(altq)

leftmeta = layer(metaq)
rightmeta = layer(metaq)

[ctrlq]
a = C-a
c = C-i
s = C-semicolon
g = C-u
v = C-dot
x = C-b
f = C-y
z = C-slash
y = C-t

t = C-k
w = C-comma
n = C-l
o = C-s
p = C-r
l = C-p
r = C-j
h = C-o
q = C-x

d = C-h
e = C-d
k = C-v
u = C-f
i = C-g
b = C-n

equal = C-equal
minus = C-minus
0 = C-0
slash = C-slash
space = C-space

leftshift = layer(ctrlshiftq)
rightshift = layer(ctrlshiftq)
leftalt = layer(ctrlaltq)

[ctrlshiftq]
z = C-S-slash
c = C-S-i
v = C-S-dot

[altq]
q = A-x
w = A-comma
e = A-d
r = A-j
t = A-k
y = A-t
u = A-f
i = A-g
o = A-s
p = A-r

a = A-a
s = A-semicolon
d = A-h
f = A-y
g = A-u
h = A-o
j = A-c
k = A-v
l = A-p
semicolon = A-l

z = A-slash
x = A-b
c = A-i
v = A-dot
b = A-n
n = A-l
m = A-m

tab = A-tab
enter = A-enter
f2 = A-f2
f4 = A-f4
left = A-left
right = A-right

leftshift = layer(altshiftq)
rightshift = layer(altshiftq)

leftcontrol = layer(ctrlaltq)
rightcontrol = layer(ctrlaltq)

[altshiftq]
tab = A-S-tab

[ctrlaltq]
t = C-A-k

[metaq]
l = M-p
d = M-h
space = M-space
a = M-a
tab = M-tab

up = M-up
down = M-down
left = M-left
right = M-right

1 = M-1
2 = M-2
3 = M-3
4 = M-4
5 = M-5
6 = M-6
7 = M-7
8 = M-8
9 = M-9
0 = M-0

pageup = M-pageup
pagedown = M-pagedown
